package edu.brook;

/**
 * Cooperate Defect Style Java Implementation.
 * 
 * Generated by metaabm system: Mar 6, 2009 1:43:18 PM PST in project: edu.brook.parent.escape  */

public class CooperateDefectStyle
		extends
			com.metascape.escape.view.gef.AgentEditPart {

	/**
	 * Constructs a new Cooperate Defect Style.
	 */

	public CooperateDefectStyle() {
		createUniqueID();
	}
	//todo, make this a useful value for evaluating compatibility of different versions of generated classes
	private static final long serialVersionUID = 89989998L;

	private String uniqueID;

	public String getUID() {
		return uniqueID;
	}

	public void createUniqueID() {
		uniqueID = org.apache.commons.lang.RandomStringUtils
				.randomAlphanumeric(5);
	}

	/**
	 * Clones the agent, ensuring that a unique id is assigned.
	 */
	public Object clone() {
		try {
			CooperateDefectStyle clone = (CooperateDefectStyle) super.clone();
			clone.createUniqueID();
			return clone;
		} catch (Exception e) {
			throw new RuntimeException("Unexpected cloning exception: " + e);
		}
	}

	org.eclipse.draw2d.geometry.Dimension notShown = new org.eclipse.draw2d.geometry.Dimension(
			0, 0);

	protected org.eclipse.draw2d.IFigure buildFigure(
			org.eclipse.draw2d.IFigure figure) {
		org.eclipse.swt.graphics.Color color = null;
		boolean createFigure = figure == null;
		org.eclipse.draw2d.Shape markerFigure = null;
		if (!createFigure) {
			((org.eclipse.draw2d.Shape) figure).setFill(false);
			((org.eclipse.draw2d.Shape) figure).setOutline(false);
		}
		Player playerRule = (Player) getModel();
		if (playerRule.isCooperate()) {

			if (!createFigure) {
				color = org.eclipse.draw2d.ColorConstants.blue;

			}
			if (createFigure) {
				figure = shapeOval();
			}

			if (!createFigure) {
				figure.setBackgroundColor(color);
				((org.eclipse.draw2d.Shape) figure).setFill(true);

			}

		}

		if (!(playerRule.isCooperate())) {

			if (!createFigure) {
				color = org.eclipse.draw2d.ColorConstants.red;

			}
			if (createFigure) {
				figure = shapeOval();
			}

			if (!createFigure) {
				figure.setBackgroundColor(color);
				((org.eclipse.draw2d.Shape) figure).setFill(true);

			}

		}

		return figure;
	}

}
