package edu.brook;

/**
 * Cooperate Defect Style Java Implementation.
 * 
 * Generated by metaabm system: Jul 10, 2009 6:08:29 PM PDT in project: edu.brook.parent.escape  */

public class CooperateDefectStyleGraphics
		extends
			org.ascape.util.vis.DrawFeature {

	enum Shapes {
		rectangle, oval, marker
	};

	Shapes shape = Shapes.rectangle;

	public void draw(org.eclipse.draw2d.Graphics g, Object object, int width,
			int height) {

		org.ascape.model.HostCell rootActGroupCell = (org.ascape.model.HostCell) object;
		if (rootActGroupCell.getOccupant() instanceof Player) {
			Player rootActGroup = (Player) rootActGroupCell.getOccupant();
			Player playerRule = rootActGroup;

			if (playerRule.isCooperate()) {
				org.eclipse.swt.graphics.Color playerRuleColorBlue = org.eclipse.draw2d.ColorConstants.blue;

				g.setForegroundColor(playerRuleColorBlue);
				g.setBackgroundColor(playerRuleColorBlue);
				shape = shape.oval;
				if (shape == Shapes.oval) {
					g.fillOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.fillOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.fillRectangle(0, 0, width, height);
				}

			}

			if (!(playerRule.isCooperate())) {
				org.eclipse.swt.graphics.Color playerRuleColorRed = org.eclipse.draw2d.ColorConstants.red;

				g.setForegroundColor(playerRuleColorRed);
				g.setBackgroundColor(playerRuleColorRed);
				shape = shape.oval;
				if (shape == Shapes.oval) {
					g.fillOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.fillOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.fillRectangle(0, 0, width, height);
				}

			}

		}
	}
}
