package edu.brook;

/**
 * Cooperate Defect Style Java Implementation.
 * 
 * Generated by metaabm system: Jul 10, 2009 6:08:11 PM PDT in project: edu.brook.parent.escape  */

public class CooperateDefectStyle extends org.eclipse.amp.agf.gef.AgentEditPart {

	org.eclipse.draw2d.geometry.Dimension notShown = new org.eclipse.draw2d.geometry.Dimension(
			0, 0);

	protected org.eclipse.draw2d.IFigure buildFigure(
			org.eclipse.draw2d.IFigure figure) {
		org.eclipse.swt.graphics.Color color = null;
		boolean createFigure = figure == null;
		org.eclipse.draw2d.Shape markerFigure = null;
		if (!createFigure) {
			((org.eclipse.draw2d.Shape) figure).setFill(false);
			((org.eclipse.draw2d.Shape) figure).setOutline(false);
		}
		Player playerRule = (Player) getModel();

		if (playerRule.isCooperate()) {

			if (!createFigure) {
				color = org.eclipse.draw2d.ColorConstants.blue;

			}
			if (createFigure) {
				figure = shapeOval();
			}

			if (!createFigure) {
				figure.setBackgroundColor(color);
				((org.eclipse.draw2d.Shape) figure).setFill(true);

			}

		}

		if (!(playerRule.isCooperate())) {

			if (!createFigure) {
				color = org.eclipse.draw2d.ColorConstants.red;

			}
			if (createFigure) {
				figure = shapeOval();
			}

			if (!createFigure) {
				figure.setBackgroundColor(color);
				((org.eclipse.draw2d.Shape) figure).setFill(true);

			}

		}

		return figure;
	}
}
