package edu.brook;

/**
 * Play Cell Java Implementation.
 * 
 * Generated by metaabm system: Mar 6, 2009 1:43:18 PM PST in project: edu.brook.parent.escape  */

public class PlayCell extends org.ascape.model.HostCell {

	/**
	 * Constructs a new Play Cell.
	 */

	public PlayCell() {
		createUniqueID();
	}
	//todo, make this a useful value for evaluating compatibility of different versions of generated classes
	private static final long serialVersionUID = 89989998L;

	private String uniqueID;

	public String getUID() {
		return uniqueID;
	}

	public void createUniqueID() {
		uniqueID = org.apache.commons.lang.RandomStringUtils
				.randomAlphanumeric(5);
	}

	/**
	 * Clones the agent, ensuring that a unique id is assigned.
	 */
	public Object clone() {
		try {
			PlayCell clone = (PlayCell) super.clone();
			clone.createUniqueID();
			return clone;
		} catch (Exception e) {
			throw new RuntimeException("Unexpected cloning exception: " + e);
		}
	}

	public DemographicPrisonersDilemma getDemographicPrisoner_sDilemma() {
		return (DemographicPrisonersDilemma) getScape().getRoot();
	}

	public String getName() {
		if (name == null) {
			return "Play Cell " + uniqueID;
		} else {
			return name;
		}
	}

}
