package edu.brook;

/**
 * Play Cell Style 2D Java Implementation.
 * 
 * Generated by metaabm system: Mar 6, 2009 1:43:18 PM PST in project: edu.brook.parent.escape  */

public class PlayCellStyle
		extends
			com.metascape.escape.view.gef.HostCellEditPart {

	/**
	 * Constructs a new Play Cell Style 2D.
	 */

	public PlayCellStyle() {
		createUniqueID();
	}
	//todo, make this a useful value for evaluating compatibility of different versions of generated classes
	private static final long serialVersionUID = 89989998L;

	private String uniqueID;

	public String getUID() {
		return uniqueID;
	}

	public void createUniqueID() {
		uniqueID = org.apache.commons.lang.RandomStringUtils
				.randomAlphanumeric(5);
	}

	/**
	 * Clones the agent, ensuring that a unique id is assigned.
	 */
	public Object clone() {
		try {
			PlayCellStyle clone = (PlayCellStyle) super.clone();
			clone.createUniqueID();
			return clone;
		} catch (Exception e) {
			throw new RuntimeException("Unexpected cloning exception: " + e);
		}
	}

	org.eclipse.draw2d.geometry.Dimension notShown = new org.eclipse.draw2d.geometry.Dimension(
			0, 0);

	protected org.eclipse.draw2d.IFigure buildFigure(
			org.eclipse.draw2d.IFigure figure) {
		org.eclipse.swt.graphics.Color color = null;
		boolean createFigure = figure == null;
		org.eclipse.draw2d.Shape markerFigure = null;
		if (!createFigure) {
			((org.eclipse.draw2d.Shape) figure).setFill(false);
			((org.eclipse.draw2d.Shape) figure).setOutline(false);
		}
		PlayCell playCellRule = (PlayCell) getModel();

		if (!createFigure) {
			color = org.eclipse.draw2d.ColorConstants.green;

		}
		if (createFigure) {
			figure = shapeRectangle();
		}

		if (!createFigure) {
			figure.setBackgroundColor(color);
			((org.eclipse.draw2d.Shape) figure).setFill(true);

		}

		return figure;
	}

}
