package edu.brook;

/**
 * Play Cell Style 2D Java Implementation.
 * 
 * Generated by metaabm system: Jul 10, 2009 6:08:29 PM PDT in project: edu.brook.parent.escape  */

public class PlayCellStyleGraphics extends org.ascape.util.vis.DrawFeature {

	enum Shapes {
		rectangle, oval, marker
	};

	Shapes shape = Shapes.rectangle;

	public void draw(org.eclipse.draw2d.Graphics g, Object object, int width,
			int height) {

		PlayCell rootActGroup = (PlayCell) object;
		PlayCell playCellRule = rootActGroup;

		org.eclipse.swt.graphics.Color playCellRuleColorGreen = org.eclipse.draw2d.ColorConstants.green;

		g.setForegroundColor(playCellRuleColorGreen);
		g.setBackgroundColor(playCellRuleColorGreen);
		shape = shape.rectangle;
		if (shape == Shapes.oval) {
			g.fillOval(0, 0, width, height);
		} else if (shape == Shapes.marker) {
			int d = (int) (width * .25 - 1);
			int d2 = (int) (width * .5 - 1);
			g.fillOval(d, d, d2, d2);
		} else if (shape == Shapes.rectangle) {
			g.fillRectangle(0, 0, width, height);
		}

	}
}
