package edu.brook;

/**
 * Play Cell Style 2D Java Implementation.
 * 
 * Generated by metaabm system: Jul 10, 2009 6:08:11 PM PDT in project: edu.brook.parent.escape  */

public class PlayCellStyle
		extends
			org.eclipse.amp.escape.ascape.gef.HostCellEditPart {

	org.eclipse.draw2d.geometry.Dimension notShown = new org.eclipse.draw2d.geometry.Dimension(
			0, 0);

	protected org.eclipse.draw2d.IFigure buildFigure(
			org.eclipse.draw2d.IFigure figure) {
		org.eclipse.swt.graphics.Color color = null;
		boolean createFigure = figure == null;
		org.eclipse.draw2d.Shape markerFigure = null;
		if (!createFigure) {
			((org.eclipse.draw2d.Shape) figure).setFill(false);
			((org.eclipse.draw2d.Shape) figure).setOutline(false);
		}
		PlayCell playCellRule = (PlayCell) getModel();

		if (!createFigure) {
			color = org.eclipse.draw2d.ColorConstants.green;

		}
		if (createFigure) {
			figure = shapeRectangle();
		}

		if (!createFigure) {
			figure.setBackgroundColor(color);
			((org.eclipse.draw2d.Shape) figure).setFill(true);

		}

		return figure;
	}
}
