package edu.brook;

/**
 * Play Cell Style 2D Java Implementation.
 * 
 * Generated by metaabm system: Jul 10, 2009 6:08:36 PM PDT in project: edu.brook.parent.escape  */

public class PlayCellStyle3DEditPart
		extends
			org.eclipse.amp.agf3d.TileEdit3DPart {

	protected void updateGraphics() {
		org.eclipse.swt.graphics.Color color = null;
		org.eclipse.draw3d.shapes.SolidCube shape = null;

		PlayCell playCellRule = (PlayCell) getModel();

		color = org.eclipse.draw2d.ColorConstants.green;

		shape = getCube();

		shape.setColor(color, 255);

	}
}
