package edu.brook.ccf.rpm;

import org.ascape.util.vis.ColorFeatureConcrete;
import org.eclipse.swt.graphics.Color;

/**
 * Neighborhood Cell Style 2D Java Implementation.
 * 
 * Generated by metaabm system: Jun 16, 2009 4:59:03 PM PDT in project: edu.brook.parent.escape  */

public class Tile3DEditPart
extends
org.eclipse.amp.agf3d.TileEdit3DPart {

    public static final Color TILE = ColorFeatureConcrete.create(240, 210, 140);

    protected void updateGraphics() {
        getCube().setColor(TILE, 255);

    }
}
