package edu.brook.ccf.rpm;

/**
 * Coital Behavior Type Java Implementation.
 * 
 * Generated by metaabm system: Oct 8, 2009 5:46:39 PM PDT in project: edu.brook.parent.escape  */

public enum CoitalBehaviorTypeEnum {
	veryLowFrequency("Very Low Frequency"), highFrequency("High Frequency"), moderateFrequency(
			"Moderate Frequency");

	private final String name;

	private CoitalBehaviorTypeEnum(String name) {
		this.name = name;
	}

	public String toString() {
		return name;
	}
}
