package edu.brook.ccf.rpm;

/**
 * Education Java Implementation.
 * 
 * Generated by metaabm system: Dec 11, 2009 6:36:38 PM PST for model: RelationshipsAndPregnancyData.metaabm in project: edu.brook.parent.escape 
 */

public enum EducationEnum {
	nHS("NHS"), pHS("PHS"), hS("HS");

	private final String name;

	private EducationEnum(String name) {
		this.name = name;
	}

	public String toString() {
		return name;
	}
}
