package edu.brook.ccf.rpm;

import org.eclipse.amp.escape.ascape.agf3d.GEF3DView;

/**
 * <!-- begin-user-doc -->
 * FamilyScape Java Implementation.
 * A model of unintended pregnancies and poor births. Covers most if not all key dynamics, including relationship and marriage formation, coital activity, contraception efficacy, and pregnancy outcome. Extensive work has been done to dock and callibrate this agent-based model with statistical models. This model will be the subject of a forthcoming paper by Thomas et. al. Current results should not be taken as definitive and are not intended for publication.

Model Design: Miles Parker and Adam Thomas (miles@metascapeabm.com, athomas@brookings.edu)
Model and Software Development: Miles Parker
Basic Research and Statistical Model: Adam Thomas and Emily Monea

Supported by The William and Flora Hewlett Foundation
 * Generated by AMF for model: FamilyScape.metaabm in project: edu.brook.parent.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class FamilyScape3D extends FamilyScape {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void createGraphicViews() {
		addView(new GEF3DView());
	}
}
