package edu.brook.ccf.rpm;

/**
 * Gender Style Java Implementation.
 * 
 * Generated by metaabm system: Dec 11, 2009 6:36:38 PM PST for model: RelationshipsAndPregnancyData.metaabm in project: edu.brook.parent.escape 
 */

public class GenderStyle extends org.eclipse.amp.agf.gef.AgentEditPart {

	org.eclipse.draw2d.geometry.Dimension notShown = new org.eclipse.draw2d.geometry.Dimension(
			0, 0);

	protected org.eclipse.draw2d.IFigure buildFigure(
			org.eclipse.draw2d.IFigure figure) {
		org.eclipse.swt.graphics.Color color = null;
		boolean createFigure = figure == null;
		org.eclipse.draw2d.Shape markerFigure = null;
		if (!createFigure) {
			((org.eclipse.draw2d.Shape) figure).setFill(false);
			((org.eclipse.draw2d.Shape) figure).setOutline(false);
		}
		Adult drawGenderRule = (Adult) getModel();

		double unitforAge = drawGenderRule.getAgeinYearsIndex() / 30.0;
		double unitforAgeRange = java.lang.Math.min(unitforAge, 1)

		;
		if (drawGenderRule.getGender() == GenderEnum.male) {

			if (createFigure) {
				figure = shapeRectangle();
			}

			if (!createFigure) {
				color = org.ascape.util.vis.ColorFeatureConcrete.create(
						(int) (unitforAgeRange * 255),
						(int) (unitforAgeRange * 255), (int) (1.0 * 255));

			}

			if (!createFigure) {
				figure.setBackgroundColor(color);
				((org.eclipse.draw2d.Shape) figure).setFill(true);

			}

			if (!createFigure) {
				color = org.eclipse.draw2d.ColorConstants.blue;

			}

			if (!createFigure) {
				figure.setForegroundColor(color);
				((org.eclipse.draw2d.Shape) figure).setOutline(true);

			}
			int now = drawGenderRule.getScape().getPeriod();
			if (now == drawGenderRule.getDayofLastSex()) {

				figure = shapeMarker();

				if (!createFigure) {
					color = org.eclipse.draw2d.ColorConstants.orange;

				}

				if (!createFigure) {
					figure.setBackgroundColor(color);
					((org.eclipse.draw2d.Shape) figure).setFill(true);

					figure = getFigure();

				}
			}

			if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {

				if (!createFigure) {
					color = org.eclipse.draw2d.ColorConstants.black;

				}

				figure = shapeMarker2();

				if (!createFigure) {
					figure.setBackgroundColor(color);
					((org.eclipse.draw2d.Shape) figure).setFill(true);

					figure = getFigure();

				}
			}

		}

		if (drawGenderRule.getGender() == GenderEnum.female) {

			if (createFigure) {
				figure = shapeOval();
			}

			if (!createFigure) {
				color = org.ascape.util.vis.ColorFeatureConcrete.create(
						(int) (1.0 * 255), (int) (unitforAgeRange * 255),
						(int) (unitforAgeRange * 255));

			}
			if (drawGenderRule.getPregnancyStatus() == PregnancyStatusEnum.pregnant) {

				if (!createFigure) {
					color = org.eclipse.draw2d.ColorConstants.green;

				}

				figure = shapeMarker3();

				if (!createFigure) {
					figure.setBackgroundColor(color);
					((org.eclipse.draw2d.Shape) figure).setFill(true);

					figure = getFigure();

				}
			}

			if (!createFigure) {
				figure.setBackgroundColor(color);
				((org.eclipse.draw2d.Shape) figure).setFill(true);

			}

			if (!createFigure) {
				color = org.eclipse.draw2d.ColorConstants.red;

			}

			if (!createFigure) {
				figure.setForegroundColor(color);
				((org.eclipse.draw2d.Shape) figure).setOutline(true);

			}
			int now = drawGenderRule.getScape().getPeriod();
			if (now == drawGenderRule.getDayofLastSex()) {

				figure = shapeMarker();

				if (!createFigure) {
					color = org.eclipse.draw2d.ColorConstants.orange;

				}

				if (!createFigure) {
					figure.setBackgroundColor(color);
					((org.eclipse.draw2d.Shape) figure).setFill(true);

					figure = getFigure();

				}
			}

			if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {

				if (!createFigure) {
					color = org.eclipse.draw2d.ColorConstants.black;

				}

				figure = shapeMarker2();

				if (!createFigure) {
					figure.setBackgroundColor(color);
					((org.eclipse.draw2d.Shape) figure).setFill(true);

					figure = getFigure();

				}
			}

		}

		return figure;
	}
}
