package edu.brook.ccf.rpm;

/**
 * Gender Style Java Implementation.
 * 
 * Generated by metaabm system: Dec 11, 2009 6:36:52 PM PST for model: RelationshipsAndPregnancyData.metaabm in project: edu.brook.parent.escape 
 */

public class GenderStyleColorProvider
		implements
			org.eclipse.jface.viewers.IColorProvider {

	/**
	 * Provides a foreground color for the given Adult.
	 * 
	 * @param object the agent
	 * @return	the foreground color for the element, or <code>null</code> 
	 *   to use the default foreground color
	 */
	public org.eclipse.swt.graphics.Color getForeground(Object object) {

		//todo separate out this functionality
		org.eclipse.swt.graphics.Color color = null;
		org.eclipse.swt.graphics.Color fillColor = null;
		org.eclipse.swt.graphics.Color outlineColor = null;
		Adult style = (Adult) object;
		Adult drawGenderRule = style;

		double unitforAge = drawGenderRule.getAgeinYearsIndex() / 30.0;
		double unitforAgeRange = java.lang.Math.min(unitforAge, 1)

		;
		if (drawGenderRule.getGender() == GenderEnum.male) {

			color = new org.eclipse.swt.graphics.Color(
					org.eclipse.swt.widgets.Display.getCurrent(),
					(int) (unitforAgeRange * 255),
					(int) (unitforAgeRange * 255), (int) (1.0 * 255));

			fillColor = color;

			color = org.eclipse.draw2d.ColorConstants.blue;

			outlineColor = color;

			int now = drawGenderRule.getScape().getPeriod();
			if (now == drawGenderRule.getDayofLastSex()) {

				color = org.eclipse.draw2d.ColorConstants.orange;

				fillColor = color;

			}
			if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {

				color = org.eclipse.draw2d.ColorConstants.black;

				fillColor = color;

			}
		}
		if (drawGenderRule.getGender() == GenderEnum.female) {

			color = new org.eclipse.swt.graphics.Color(
					org.eclipse.swt.widgets.Display.getCurrent(),
					(int) (1.0 * 255), (int) (unitforAgeRange * 255),
					(int) (unitforAgeRange * 255));

			if (drawGenderRule.getPregnancyStatus() == PregnancyStatusEnum.pregnant) {

				color = org.eclipse.draw2d.ColorConstants.green;

				fillColor = color;

			}

			fillColor = color;

			color = org.eclipse.draw2d.ColorConstants.red;

			outlineColor = color;

			int now = drawGenderRule.getScape().getPeriod();
			if (now == drawGenderRule.getDayofLastSex()) {

				color = org.eclipse.draw2d.ColorConstants.orange;

				fillColor = color;

			}
			if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {

				color = org.eclipse.draw2d.ColorConstants.black;

				fillColor = color;

			}
		}

		if (outlineColor != null) {
			return outlineColor;
		} else if (fillColor != null) {
			return fillColor;
		}
		return org.ascape.util.vis.ColorFeature.BLACK;
	}

	/**
	 * Provides a background color for the given Adult.
	 * 
	 * @param object the agent
	 * @return	the background color for the element, or <code>null</code> 
	 *   to use the default background color
	 */
	public org.eclipse.swt.graphics.Color getBackground(Object object) {

		//todo separate out this functionality
		org.eclipse.swt.graphics.Color color = null;
		org.eclipse.swt.graphics.Color fillColor = null;
		org.eclipse.swt.graphics.Color outlineColor = null;
		Adult style = (Adult) object;
		Adult drawGenderRule = style;

		double unitforAge = drawGenderRule.getAgeinYearsIndex() / 30.0;
		double unitforAgeRange = java.lang.Math.min(unitforAge, 1)

		;
		if (drawGenderRule.getGender() == GenderEnum.male) {

			color = new org.eclipse.swt.graphics.Color(
					org.eclipse.swt.widgets.Display.getCurrent(),
					(int) (unitforAgeRange * 255),
					(int) (unitforAgeRange * 255), (int) (1.0 * 255));

			fillColor = color;

			color = org.eclipse.draw2d.ColorConstants.blue;

			outlineColor = color;

			int now = drawGenderRule.getScape().getPeriod();
			if (now == drawGenderRule.getDayofLastSex()) {

				color = org.eclipse.draw2d.ColorConstants.orange;

				fillColor = color;

			}
			if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {

				color = org.eclipse.draw2d.ColorConstants.black;

				fillColor = color;

			}
		}
		if (drawGenderRule.getGender() == GenderEnum.female) {

			color = new org.eclipse.swt.graphics.Color(
					org.eclipse.swt.widgets.Display.getCurrent(),
					(int) (1.0 * 255), (int) (unitforAgeRange * 255),
					(int) (unitforAgeRange * 255));

			if (drawGenderRule.getPregnancyStatus() == PregnancyStatusEnum.pregnant) {

				color = org.eclipse.draw2d.ColorConstants.green;

				fillColor = color;

			}

			fillColor = color;

			color = org.eclipse.draw2d.ColorConstants.red;

			outlineColor = color;

			int now = drawGenderRule.getScape().getPeriod();
			if (now == drawGenderRule.getDayofLastSex()) {

				color = org.eclipse.draw2d.ColorConstants.orange;

				fillColor = color;

			}
			if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {

				color = org.eclipse.draw2d.ColorConstants.black;

				fillColor = color;

			}
		}

		if (fillColor != null) {
			return fillColor;
		} else if (outlineColor != null) {
			return outlineColor;
		}
		return org.ascape.util.vis.ColorFeature.BLACK;
	}
}
