package edu.brook.ccf.rpm;

/**
 * Gender Style Java Implementation.
 * 
 * Generated by metaabm system: Mar 4, 2009 8:09:53 PM PST in project: edu.brook.parent.escape  */

public class GenderStyleGraphics
		extends
			com.metascape.escape.view.vis.util.DrawFeature {

	/**
	 * Constructs a new Gender Style.
	 */

	public GenderStyleGraphics() {
		createUniqueID();
	}
	//todo, make this a useful value for evaluating compatibility of different versions of generated classes
	private static final long serialVersionUID = 89989998L;

	private String uniqueID;

	public String getUID() {
		return uniqueID;
	}

	public void createUniqueID() {
		uniqueID = org.apache.commons.lang.RandomStringUtils
				.randomAlphanumeric(5);
	}

	/**
	 * Clones the agent, ensuring that a unique id is assigned.
	 */
	public Object clone() {
		try {
			GenderStyle clone = (GenderStyle) super.clone();
			clone.createUniqueID();
			return clone;
		} catch (Exception e) {
			throw new RuntimeException("Unexpected cloning exception: " + e);
		}
	}

	enum Shapes {
		rectangle, oval, marker
	};

	Shapes shape = Shapes.rectangle;

	public void draw(org.eclipse.draw2d.Graphics g, Object object, int width,
			int height) {
		org.ascape.model.HostCell drawGenderRuleCell = (org.ascape.model.HostCell) object;
		if (drawGenderRuleCell.getOccupant() instanceof Adult) {
			Adult drawGenderRule = (Adult) drawGenderRuleCell.getOccupant();

			double unitforAge = drawGenderRule.getAgeinYearsIndex() / 30.0;

			if (drawGenderRule.getGender() == GenderEnum.male) {
				shape = shape.rectangle;
				org.eclipse.swt.graphics.Color blueScale = new org.eclipse.swt.graphics.Color(
						org.eclipse.swt.widgets.Display.getCurrent(),
						(int) (unitforAge * 255), (int) (unitforAge * 255),
						(int) (1.0 * 255));

				g.setForegroundColor(blueScale);
				g.setBackgroundColor(blueScale);
				if (shape == Shapes.oval) {
					g.fillOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.fillOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.fillRectangle(0, 0, width, height);
				}
				org.eclipse.swt.graphics.Color maleColor = org.eclipse.draw2d.ColorConstants.blue;

				g.setForegroundColor(maleColor);
				g.setBackgroundColor(maleColor);
				if (shape == Shapes.oval) {
					g.drawOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.drawOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.drawRectangle(0, 0, width, height);
				}

				int now = drawGenderRule.getScape().getPeriod();

				if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {
					org.eclipse.swt.graphics.Color drawGenderRule_Unspecified_ = org.eclipse.draw2d.ColorConstants.black;

					g.setForegroundColor(drawGenderRule_Unspecified_);
					g.setBackgroundColor(drawGenderRule_Unspecified_);
					shape = shape.marker;
					if (shape == Shapes.oval) {
						g.fillOval(0, 0, width, height);
					} else if (shape == Shapes.marker) {
						int d = (int) (width * .25 - 1);
						int d2 = (int) (width * .5 - 1);
						g.fillOval(d, d, d2, d2);
					} else if (shape == Shapes.rectangle) {
						g.fillRectangle(0, 0, width, height);
					}

				}

				if (now == drawGenderRule.getDayofLastSex()) {
					org.eclipse.swt.graphics.Color sexColor = org.eclipse.draw2d.ColorConstants.orange;

					g.setForegroundColor(sexColor);
					g.setBackgroundColor(sexColor);
					if (shape == Shapes.oval) {
						g.fillOval(0, 0, width, height);
					} else if (shape == Shapes.marker) {
						int d = (int) (width * .25 - 1);
						int d2 = (int) (width * .5 - 1);
						g.fillOval(d, d, d2, d2);
					} else if (shape == Shapes.rectangle) {
						g.fillRectangle(0, 0, width, height);
					}

				}

			}

			if (drawGenderRule.getGender() == GenderEnum.female) {
				shape = shape.oval;
				if (drawGenderRule.isPregnant()) {
					org.eclipse.swt.graphics.Color greenScale = new org.eclipse.swt.graphics.Color(
							org.eclipse.swt.widgets.Display.getCurrent(),
							(int) (unitforAge * 255), (int) (1.0 * 255),
							(int) (unitforAge * 255));

					g.setForegroundColor(greenScale);
					g.setBackgroundColor(greenScale);
					if (shape == Shapes.oval) {
						g.fillOval(0, 0, width, height);
					} else if (shape == Shapes.marker) {
						int d = (int) (width * .25 - 1);
						int d2 = (int) (width * .5 - 1);
						g.fillOval(d, d, d2, d2);
					} else if (shape == Shapes.rectangle) {
						g.fillRectangle(0, 0, width, height);
					}
					org.eclipse.swt.graphics.Color pregnantColor = org.eclipse.draw2d.ColorConstants.green;

					g.setForegroundColor(pregnantColor);
					g.setBackgroundColor(pregnantColor);
					if (shape == Shapes.oval) {
						g.drawOval(0, 0, width, height);
					} else if (shape == Shapes.marker) {
						int d = (int) (width * .25 - 1);
						int d2 = (int) (width * .5 - 1);
						g.drawOval(d, d, d2, d2);
					} else if (shape == Shapes.rectangle) {
						g.drawRectangle(0, 0, width, height);
					}

					int now = drawGenderRule.getScape().getPeriod();

					if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {
						org.eclipse.swt.graphics.Color drawGenderRule_Unspecified_ = org.eclipse.draw2d.ColorConstants.black;

						g.setForegroundColor(drawGenderRule_Unspecified_);
						g.setBackgroundColor(drawGenderRule_Unspecified_);
						shape = shape.marker;
						if (shape == Shapes.oval) {
							g.fillOval(0, 0, width, height);
						} else if (shape == Shapes.marker) {
							int d = (int) (width * .25 - 1);
							int d2 = (int) (width * .5 - 1);
							g.fillOval(d, d, d2, d2);
						} else if (shape == Shapes.rectangle) {
							g.fillRectangle(0, 0, width, height);
						}

					}

					if (now == drawGenderRule.getDayofLastSex()) {
						org.eclipse.swt.graphics.Color sexColor = org.eclipse.draw2d.ColorConstants.orange;

						g.setForegroundColor(sexColor);
						g.setBackgroundColor(sexColor);
						if (shape == Shapes.oval) {
							g.fillOval(0, 0, width, height);
						} else if (shape == Shapes.marker) {
							int d = (int) (width * .25 - 1);
							int d2 = (int) (width * .5 - 1);
							g.fillOval(d, d, d2, d2);
						} else if (shape == Shapes.rectangle) {
							g.fillRectangle(0, 0, width, height);
						}

					}

				}

				if (!drawGenderRule.isPregnant()) {
					org.eclipse.swt.graphics.Color redScale = new org.eclipse.swt.graphics.Color(
							org.eclipse.swt.widgets.Display.getCurrent(),
							(int) (1.0 * 255), (int) (unitforAge * 255),
							(int) (unitforAge * 255));

					g.setForegroundColor(redScale);
					g.setBackgroundColor(redScale);
					if (shape == Shapes.oval) {
						g.fillOval(0, 0, width, height);
					} else if (shape == Shapes.marker) {
						int d = (int) (width * .25 - 1);
						int d2 = (int) (width * .5 - 1);
						g.fillOval(d, d, d2, d2);
					} else if (shape == Shapes.rectangle) {
						g.fillRectangle(0, 0, width, height);
					}
					org.eclipse.swt.graphics.Color notPregnantColor = org.eclipse.draw2d.ColorConstants.red;

					g.setForegroundColor(notPregnantColor);
					g.setBackgroundColor(notPregnantColor);
					if (shape == Shapes.oval) {
						g.drawOval(0, 0, width, height);
					} else if (shape == Shapes.marker) {
						int d = (int) (width * .25 - 1);
						int d2 = (int) (width * .5 - 1);
						g.drawOval(d, d, d2, d2);
					} else if (shape == Shapes.rectangle) {
						g.drawRectangle(0, 0, width, height);
					}

					int now = drawGenderRule.getScape().getPeriod();

					if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {
						org.eclipse.swt.graphics.Color drawGenderRule_Unspecified_ = org.eclipse.draw2d.ColorConstants.black;

						g.setForegroundColor(drawGenderRule_Unspecified_);
						g.setBackgroundColor(drawGenderRule_Unspecified_);
						shape = shape.marker;
						if (shape == Shapes.oval) {
							g.fillOval(0, 0, width, height);
						} else if (shape == Shapes.marker) {
							int d = (int) (width * .25 - 1);
							int d2 = (int) (width * .5 - 1);
							g.fillOval(d, d, d2, d2);
						} else if (shape == Shapes.rectangle) {
							g.fillRectangle(0, 0, width, height);
						}

					}

					if (now == drawGenderRule.getDayofLastSex()) {
						org.eclipse.swt.graphics.Color sexColor = org.eclipse.draw2d.ColorConstants.orange;

						g.setForegroundColor(sexColor);
						g.setBackgroundColor(sexColor);
						if (shape == Shapes.oval) {
							g.fillOval(0, 0, width, height);
						} else if (shape == Shapes.marker) {
							int d = (int) (width * .25 - 1);
							int d2 = (int) (width * .5 - 1);
							g.fillOval(d, d, d2, d2);
						} else if (shape == Shapes.rectangle) {
							g.fillRectangle(0, 0, width, height);
						}

					}

				}

			}

		}
	}
}
