package edu.brook.ccf.rpm;

/**
 * Gender Style Java Implementation.
 * 
 * Generated by metaabm system: Oct 8, 2009 5:46:57 PM PDT in project: edu.brook.parent.escape  */

public class GenderStyle3DEditPart extends org.eclipse.amp.agf3d.CubeEdit3DPart {

	protected void updateGraphics() {
		org.eclipse.swt.graphics.Color color = null;
		org.eclipse.draw3d.shapes.SolidCube shape = null;

		for (int i = 1; i <= 4; i++) {
			setShowMarker(i, false);
		}

		Adult drawGenderRule = (Adult) getModel();

		double unitforAge = drawGenderRule.getAgeinYearsIndex() / 30.0;

		double unitforAgeRange = java.lang.Math.min(unitforAge, 1)

		;

		if (drawGenderRule.getGender() == GenderEnum.male) {
			shape = getCube();

			color = org.ascape.util.vis.ColorFeatureConcrete.create(
					(int) (unitforAgeRange * 255),
					(int) (unitforAgeRange * 255), (int) (1.0 * 255));

			shape.setColor(color, 255);

			color = org.eclipse.draw2d.ColorConstants.blue;

			//outline: shape.setColor(color, 255);

			int now = drawGenderRule.getScape().getPeriod();

			if (now == drawGenderRule.getDayofLastSex()) {

				setShowMarker(1, true);
				shape = getMarker(1);

				color = org.eclipse.draw2d.ColorConstants.orange;

				shape.setColor(color, 255);

			}

			if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {

				color = org.eclipse.draw2d.ColorConstants.black;

				setShowMarker(2, true);
				shape = getMarker(2);

				shape.setColor(color, 255);

			}

		}

		if (drawGenderRule.getGender() == GenderEnum.female) {
			shape = getCube();

			color = org.ascape.util.vis.ColorFeatureConcrete.create(
					(int) (1.0 * 255), (int) (unitforAgeRange * 255),
					(int) (unitforAgeRange * 255));

			if (drawGenderRule.isPregnant()) {

				color = org.eclipse.draw2d.ColorConstants.green;

				setShowMarker(3, true);
				shape = getMarker(3);

				shape.setColor(color, 255);

			}

			shape.setColor(color, 255);

			color = org.eclipse.draw2d.ColorConstants.red;

			//outline: shape.setColor(color, 255);

			int now = drawGenderRule.getScape().getPeriod();

			if (now == drawGenderRule.getDayofLastSex()) {

				setShowMarker(1, true);
				shape = getMarker(1);

				color = org.eclipse.draw2d.ColorConstants.orange;

				shape.setColor(color, 255);

			}

			if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {

				color = org.eclipse.draw2d.ColorConstants.black;

				setShowMarker(2, true);
				shape = getMarker(2);

				shape.setColor(color, 255);

			}

		}

	}
}
