package edu.brook.ccf.rpm;

import org.eclipse.draw2d.ColorConstants;
import org.eclipse.draw2d.Graphics;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.widgets.Display;

import org.ascape.model.Agent;
import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;

import org.ascape.util.vis.DrawFeature;

/**
 * Gender Style Java Implementation.
 * 
 * Generated by AMF for model: RelationshipsAndPregnancyData.metaabm in project: edu.brook.parent.escape 
 */

public class GenderStyleGraphics extends DrawFeature {

	enum Shapes {
		rectangle, oval, marker
	};

	Shapes shape = Shapes.rectangle;

	public void draw(Graphics g, Object object, int width, int height) {

		HostCell styleCell = (HostCell) object;
		if (styleCell.getOccupant() instanceof Adult) {
			Adult style = (Adult) styleCell.getOccupant();
			Adult drawGenderRule = style;

			double unitforAge = drawGenderRule.getAgeinYearsIndex() / 30.0;

			double unitforAgeRange = java.lang.Math.min(unitforAge, 1)

			;
			if (drawGenderRule.getGender() == GenderEnum.male) {
				shape = shape.rectangle;
				Color blueScale = new Color(Display.getCurrent(),
						(int) (unitforAgeRange * 255),
						(int) (unitforAgeRange * 255), (int) (1.0 * 255));
				g.setForegroundColor(blueScale);
				g.setBackgroundColor(blueScale);
				if (shape == Shapes.oval) {
					g.fillOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.fillOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.fillRectangle(0, 0, width, height);
				}
				Color maleColor = ColorConstants.blue;
				g.setForegroundColor(maleColor);
				g.setBackgroundColor(maleColor);
				if (shape == Shapes.oval) {
					g.drawOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.drawOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.drawRectangle(0, 0, width, height);
				}

				int now = drawGenderRule.getScape().getPeriod();
				if (now == drawGenderRule.getDayofLastSex()) {
					shape = shape.marker;
					Color sexColor = ColorConstants.orange;
					g.setForegroundColor(sexColor);
					g.setBackgroundColor(sexColor);
					if (shape == Shapes.oval) {
						g.fillOval(0, 0, width, height);
					} else if (shape == Shapes.marker) {
						int d = (int) (width * .25 - 1);
						int d2 = (int) (width * .5 - 1);
						g.fillOval(d, d, d2, d2);
					} else if (shape == Shapes.rectangle) {
						g.fillRectangle(0, 0, width, height);
					}
				}
				if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {
					Color colorBlack = ColorConstants.black;
					g.setForegroundColor(colorBlack);
					g.setBackgroundColor(colorBlack);
					shape = shape.marker;
					if (shape == Shapes.oval) {
						g.fillOval(0, 0, width, height);
					} else if (shape == Shapes.marker) {
						int d = (int) (width * .25 - 1);
						int d2 = (int) (width * .5 - 1);
						g.fillOval(d, d, d2, d2);
					} else if (shape == Shapes.rectangle) {
						g.fillRectangle(0, 0, width, height);
					}
				}
			}
			if (drawGenderRule.getGender() == GenderEnum.female) {
				shape = shape.oval;
				Color redScale = new Color(Display.getCurrent(),
						(int) (1.0 * 255), (int) (unitforAgeRange * 255),
						(int) (unitforAgeRange * 255));
				g.setForegroundColor(redScale);
				g.setBackgroundColor(redScale);
				if (drawGenderRule.getPregnancyStatus() == PregnancyStatusEnum.pregnant) {
					Color drawGenderRuleColorGreen = ColorConstants.green;
					g.setForegroundColor(drawGenderRuleColorGreen);
					g.setBackgroundColor(drawGenderRuleColorGreen);
					shape = shape.marker;
					if (shape == Shapes.oval) {
						g.fillOval(0, 0, width, height);
					} else if (shape == Shapes.marker) {
						int d = (int) (width * .25 - 1);
						int d2 = (int) (width * .5 - 1);
						g.fillOval(d, d, d2, d2);
					} else if (shape == Shapes.rectangle) {
						g.fillRectangle(0, 0, width, height);
					}
				}
				if (shape == Shapes.oval) {
					g.fillOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.fillOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.fillRectangle(0, 0, width, height);
				}
				Color notPregnantColor = ColorConstants.red;
				g.setForegroundColor(notPregnantColor);
				g.setBackgroundColor(notPregnantColor);
				if (shape == Shapes.oval) {
					g.drawOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.drawOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.drawRectangle(0, 0, width, height);
				}

				int now = drawGenderRule.getScape().getPeriod();
				if (now == drawGenderRule.getDayofLastSex()) {
					shape = shape.marker;
					Color sexColor = ColorConstants.orange;
					g.setForegroundColor(sexColor);
					g.setBackgroundColor(sexColor);
					if (shape == Shapes.oval) {
						g.fillOval(0, 0, width, height);
					} else if (shape == Shapes.marker) {
						int d = (int) (width * .25 - 1);
						int d2 = (int) (width * .5 - 1);
						g.fillOval(d, d, d2, d2);
					} else if (shape == Shapes.rectangle) {
						g.fillRectangle(0, 0, width, height);
					}
				}
				if (drawGenderRule.getMaritalStatus() == MaritalStatusEnum.married) {
					Color colorBlack = ColorConstants.black;
					g.setForegroundColor(colorBlack);
					g.setBackgroundColor(colorBlack);
					shape = shape.marker;
					if (shape == Shapes.oval) {
						g.fillOval(0, 0, width, height);
					} else if (shape == Shapes.marker) {
						int d = (int) (width * .25 - 1);
						int d2 = (int) (width * .5 - 1);
						g.fillOval(d, d, d2, d2);
					} else if (shape == Shapes.rectangle) {
						g.fillRectangle(0, 0, width, height);
					}
				}
			}

		}
	}
}
