package edu.brook.ccf.rpm;

/**
 * Gender Java Implementation.
 * 
 * Generated by metaabm system: Apr 10, 2009 2:03:20 PM PDT in project: edu.brook.parent.escape  */

public enum GenderEnum {
	female("Female"), male("Male");

	private final String name;

	private GenderEnum(String name) {
		this.name = name;
	}

	public String toString() {
		return name;
	}
}
