package edu.brook.ccf.rpm;

/**
 * Gender Java Implementation.
 * 
 * Generated by metaabm system: Feb 16, 2010 7:31:53 PM PST for model: RelationshipsAndPregnancyData.metaabm in project: edu.brook.parent.escape 
 */

public enum GenderEnum {
	female("Female"), male("Male");

	private final String name;

	private GenderEnum(String name) {
		this.name = name;
	}

	public String toString() {
		return name;
	}
}
