package edu.brook.ccf.rpm;

/**
 * <!-- begin-user-doc -->
 * Gender Style Java Implementation.
 * 
 * Generated by AMF for model: FamilyScape.metaabm in project: edu.brook.parent.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class GenderStyle {

}
