package edu.brook.ccf.rpm;

/**
 * Marital Status Java Implementation.
 * 
 * Generated by metaabm system: Feb 16, 2010 7:31:53 PM PST for model: RelationshipsAndPregnancyData.metaabm in project: edu.brook.parent.escape 
 */

public enum MaritalStatusEnum {
	married("Married"), single("Single"), divorced("Divorced");

	private final String name;

	private MaritalStatusEnum(String name) {
		this.name = name;
	}

	public String toString() {
		return name;
	}
}
