package edu.brook.ccf.rpm;

/**
 * Marital Status Java Implementation.
 * 
 * Generated by metaabm system: Apr 10, 2009 2:03:20 PM PDT in project: edu.brook.parent.escape  */

public enum MaritalStatusEnum {
	married("Married"), single("Single"), divorced("Divorced");

	private final String name;

	private MaritalStatusEnum(String name) {
		this.name = name;
	}

	public String toString() {
		return name;
	}
}
