package edu.brook.ccf.rpm;

import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;
import org.ascape.util.vis.ColorFeatureConcrete;
import org.eclipse.draw2d.ColorConstants;
import org.eclipse.draw2d.IFigure;
import org.eclipse.draw2d.Shape;
import org.eclipse.draw2d.geometry.Dimension;
import org.eclipse.swt.graphics.Color;
import org.eclipse.amp.agf.gef.AgentEditPart;
import org.eclipse.amp.escape.ascape.gef.HostCellEditPart;

/**
 * Neighborhood Cell Style 2D Java Implementation.
 * 
 * Generated by AMF for model: RPP3D.metaabm in project: edu.brook.parent.escape 
 */

public class NeighborhoodCellStyle2D extends HostCellEditPart {

	Dimension notShown = new Dimension(0, 0);

	protected IFigure buildFigure(IFigure figure) {
		Color color = null;
		boolean createFigure = figure == null;
		Shape markerFigure = null;
		if (!createFigure) {
			((Shape) figure).setFill(false);
			((Shape) figure).setOutline(false);
		}
		NeighborhoodCell background = (NeighborhoodCell) getModel();

		if (!createFigure) {
			color = ColorConstants.gray;

		}
		if (createFigure) {
			figure = shapeRectangle();
		}

		if (!createFigure) {
			figure.setBackgroundColor(color);
			((Shape) figure).setFill(true);

		}

		return figure;
	}
}
