package edu.brook.ccf.rpm;

/**
 * Neighborhood Cell Java Implementation.
 * 
 * Generated by metaabm system: Feb 16, 2010 7:31:53 PM PST for model: RelationshipsAndPregnancyData.metaabm in project: edu.brook.parent.escape 
 */

public class NeighborhoodCell extends org.ascape.model.HostCell {

	/**
	 * Constructs a new Neighborhood Cell.
	 */

	public NeighborhoodCell() {
	}
	//todo, make this a useful value for evaluating compatibility of different versions of generated classes
	private static final long serialVersionUID = 89989998L;

	private static long nextUniqueID;

	private long uniqueID;

	public long getUID() {
		if (uniqueID == 0) {
			uniqueID = nextUniqueID++;
		}
		return uniqueID;
	}

	/**
	 * Clones the agent, ensuring that a unique id is assigned.
	 */
	public Object clone() {
		try {
			NeighborhoodCell clone = (NeighborhoodCell) super.clone();
			clone.uniqueID = 0;
			return clone;
		} catch (Exception e) {
			throw new RuntimeException("Unexpected cloning exception: " + e);
		}
	}

	public RelationshipsAndPregnancy getRelationshipsAndPregnancy() {
		return (RelationshipsAndPregnancy) getScape().getScape();
	}

	public java.util.List getNetwork() {
		return ((org.ascape.model.space.Graph) getRelationshipsAndPregnancy()
				.getPartners().getSpace()).getNeighborsFor(this);
	}

	public String getName() {
		if (name == null) {
			return "Neighborhood Cell " + getUID();
		} else {
			return name;
		}
	}
}
