package edu.brook.ccf.rpm;

/**
 * <!-- begin-user-doc -->
 * Neighborhood Cell Style 2D Java Implementation.
 * 
 * Generated by AMF for model: FamilyScape.metaabm in project: edu.brook.parent.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class NeighborhoodCellStyle2D {

}
