package edu.brook.ccf.rpm;

/**
 * Neighborhood Cell Style 2D Java Implementation.
 * 
 * Generated by metaabm system: Feb 16, 2010 7:32:10 PM PST for model: RPP3D.metaabm in project: edu.brook.parent.escape 
 */

public class NeighborhoodCellStyle2DColorProvider
		implements
			org.eclipse.jface.viewers.IColorProvider {

	/**
	 * Provides a foreground color for the given Neighborhood Cell.
	 * 
	 * @param object the agent
	 * @return	the foreground color for the element, or <code>null</code> 
	 *   to use the default foreground color
	 */
	public org.eclipse.swt.graphics.Color getForeground(Object object) {

		//todo separate out this functionality
		org.eclipse.swt.graphics.Color color = null;
		org.eclipse.swt.graphics.Color fillColor = null;
		org.eclipse.swt.graphics.Color outlineColor = null;
		NeighborhoodCell rootActGroup = (NeighborhoodCell) object;
		NeighborhoodCell background = rootActGroup;

		color = org.eclipse.draw2d.ColorConstants.gray;

		fillColor = color;

		if (outlineColor != null) {
			return outlineColor;
		} else if (fillColor != null) {
			return fillColor;
		}
		return org.ascape.util.vis.ColorFeature.BLACK;
	}

	/**
	 * Provides a background color for the given Neighborhood Cell.
	 * 
	 * @param object the agent
	 * @return	the background color for the element, or <code>null</code> 
	 *   to use the default background color
	 */
	public org.eclipse.swt.graphics.Color getBackground(Object object) {

		//todo separate out this functionality
		org.eclipse.swt.graphics.Color color = null;
		org.eclipse.swt.graphics.Color fillColor = null;
		org.eclipse.swt.graphics.Color outlineColor = null;
		NeighborhoodCell rootActGroup = (NeighborhoodCell) object;
		NeighborhoodCell background = rootActGroup;

		color = org.eclipse.draw2d.ColorConstants.gray;

		fillColor = color;

		if (fillColor != null) {
			return fillColor;
		} else if (outlineColor != null) {
			return outlineColor;
		}
		return org.ascape.util.vis.ColorFeature.BLACK;
	}
}
