package edu.brook.ccf.rpm;

import org.ascape.util.vis.ColorFeature;
import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.widgets.Display;
import org.eclipse.draw2d.Shape;
import org.eclipse.draw2d.ColorConstants;

import org.eclipse.jface.viewers.IColorProvider;

/**
 * Neighborhood Cell Style 2D Java Implementation.
 * 
 * Generated by AMF for model: RPP3D.metaabm in project: edu.brook.parent.escape 
 */

public class NeighborhoodCellStyle2DColorProvider implements IColorProvider {

	/**
	 * Provides a foreground color for the given Neighborhood Cell.
	 * 
	 * @param object the agent
	 * @return	the foreground color for the element, or <code>null</code> 
	 *   to use the default foreground color
	 */
	public Color getForeground(Object object) {

		//todo separate out this functionality
		Color color = null;
		Color fillColor = null;
		Color outlineColor = null;
		NeighborhoodCell rootActGroup = (NeighborhoodCell) object;
		NeighborhoodCell background = rootActGroup;

		color = ColorConstants.gray;

		fillColor = color;

		if (outlineColor != null) {
			return outlineColor;
		} else if (fillColor != null) {
			return fillColor;
		}
		return ColorFeature.BLACK;
	}

	/**
	 * Provides a background color for the given Neighborhood Cell.
	 * 
	 * @param object the agent
	 * @return	the background color for the element, or <code>null</code> 
	 *   to use the default background color
	 */
	public Color getBackground(Object object) {

		//todo separate out this functionality
		Color color = null;
		Color fillColor = null;
		Color outlineColor = null;
		NeighborhoodCell rootActGroup = (NeighborhoodCell) object;
		NeighborhoodCell background = rootActGroup;

		color = ColorConstants.gray;

		fillColor = color;

		if (fillColor != null) {
			return fillColor;
		} else if (outlineColor != null) {
			return outlineColor;
		}
		return ColorFeature.BLACK;
	}
}
