package edu.brook.ccf.rpm;

/**
 * Neighborhood Cell Style 2D Java Implementation.
 * 
 * Generated by metaabm system: Mar 4, 2009 8:09:53 PM PST in project: edu.brook.parent.escape  */

public class NeighborhoodCellStyle2DGraphics
		extends
			com.metascape.escape.view.vis.util.DrawFeature {

	/**
	 * Constructs a new Neighborhood Cell Style 2D.
	 */

	public NeighborhoodCellStyle2DGraphics() {
		createUniqueID();
	}
	//todo, make this a useful value for evaluating compatibility of different versions of generated classes
	private static final long serialVersionUID = 89989998L;

	private String uniqueID;

	public String getUID() {
		return uniqueID;
	}

	public void createUniqueID() {
		uniqueID = org.apache.commons.lang.RandomStringUtils
				.randomAlphanumeric(5);
	}

	/**
	 * Clones the agent, ensuring that a unique id is assigned.
	 */
	public Object clone() {
		try {
			NeighborhoodCellStyle2D clone = (NeighborhoodCellStyle2D) super
					.clone();
			clone.createUniqueID();
			return clone;
		} catch (Exception e) {
			throw new RuntimeException("Unexpected cloning exception: " + e);
		}
	}

	enum Shapes {
		rectangle, oval, marker
	};

	Shapes shape = Shapes.rectangle;

	public void draw(org.eclipse.draw2d.Graphics g, Object object, int width,
			int height) {
		NeighborhoodCell background = (NeighborhoodCell) object;
		org.eclipse.swt.graphics.Color backgroundColorWhite = org.eclipse.draw2d.ColorConstants.white;

		g.setForegroundColor(backgroundColorWhite);
		g.setBackgroundColor(backgroundColorWhite);
		shape = shape.rectangle;
		if (shape == Shapes.oval) {
			g.fillOval(0, 0, width, height);
		} else if (shape == Shapes.marker) {
			int d = (int) (width * .25 - 1);
			int d2 = (int) (width * .5 - 1);
			g.fillOval(d, d, d2, d2);
		} else if (shape == Shapes.rectangle) {
			g.fillRectangle(0, 0, width, height);
		}

	}
}
