package edu.brook.ccf.rpm;

/**
 * Partner Contraception Method Java Implementation.
 * 
 * Generated by metaabm system: Apr 10, 2009 2:03:20 PM PDT in project: edu.brook.parent.escape  */

public enum PartnerContraceptionMethodEnum {
	partnerSterilized("Partner Sterilized"), otherContraception(
			"Other Contraception");

	private final String name;

	private PartnerContraceptionMethodEnum(String name) {
		this.name = name;
	}

	public String toString() {
		return name;
	}
}
