package edu.brook.ccf.rpm;

/**
 * Pregnancy Status Couple Java Implementation.
 * 
 * Generated by AMF for model: FamilyScape.metaabm in project: edu.brook.parent.escape 
 */
public enum PregnancyStatusCoupleEnum {
	notPregnant("Not Pregnant"), pregnant("Pregnant"), notInCouple(
			"Not In Couple");

	private final String name;

	private PregnancyStatusCoupleEnum(String name) {
		this.name = name;
	}

	public String toString() {
		return name;
	}
}
