package edu.brook.ccf.rpm;

/**
 * Pregnancy Status Java Implementation.
 * 
 * Generated by metaabm system: Nov 20, 2009 7:01:25 PM PST in project: edu.brook.parent.escape  */

public enum PregnancyStatusEnum {
	notPregnant("Not Pregnant"), pregnant("Pregnant");

	private final String name;

	private PregnancyStatusEnum(String name) {
		this.name = name;
	}

	public String toString() {
		return name;
	}
}
