package edu.brook.ccf.rpm;

/**
 * Race Java Implementation.
 * 
 * Generated by AMF for model: RelationshipsAndPregnancyData.metaabm in project: edu.brook.parent.escape 
 */
public enum RaceEnum {
	other("Other"), black("Black"), hispanic("Hispanic"), white("White");

	private final String name;

	private RaceEnum(String name) {
		this.name = name;
	}

	public String toString() {
		return name;
	}
}
