package edu.brook.ccf.rpm;

/**
 * Race Java Implementation.
 * 
 * Generated by metaabm system: Jul 10, 2009 6:08:26 PM PDT in project: edu.brook.parent.escape  */

public enum RaceEnum {
	other("Other"), black("Black"), hispanic("Hispanic"), white("White");

	private final String name;

	private RaceEnum(String name) {
		this.name = name;
	}

	public String toString() {
		return name;
	}
}
