package edu.brook.ccf.rpm;

/**
 * Race Java Implementation.
 * 
 * Generated by metaabm system: Dec 11, 2009 6:36:38 PM PST for model: RelationshipsAndPregnancyData.metaabm in project: edu.brook.parent.escape 
 */

public enum RaceEnum {
	other("Other"), black("Black"), hispanic("Hispanic"), white("White");

	private final String name;

	private RaceEnum(String name) {
		this.name = name;
	}

	public String toString() {
		return name;
	}
}
