package edu.brook.ccf.rpm;

/**
 * Relationships And Pregnancy Java Implementation.
 * 
 * Generated by metaabm system: Feb 16, 2010 7:32:08 PM PST in project: edu.brook.parent.escape  */
public class RelationshipsAndPregnancy3D extends RelationshipsAndPregnancy
		implements
			org.eclipse.amp.agf3d.I3DModelFactoryProvider {
	public void createGraphicViews() {
		addView(new org.eclipse.amp.escape.ascape.agf3d.GEF3DView());
	}

	public org.eclipse.gef.EditPartFactory getEditPart3DFactory() {
		return new org.eclipse.amp.escape.ascape.adapt.Ascape3DPartFactory() {
			public org.eclipse.jface.viewers.IColorProvider getColorProvider(
					Object model) {

				if (model instanceof Adult) {
					return new edu.brook.ccf.rpm.GenderStyleColorProvider();
				}

				if (model instanceof NeighborhoodCell) {
					return new edu.brook.ccf.rpm.NeighborhoodCellStyle2DColorProvider();
				}

				return null;
			}
		};
	}

}
