package edu.brook.ccf.rpm;

import org.eclipse.amp.escape.ascape.agf3d.GEF3DView;

/**
 * Relationships And Pregnancy Java Implementation.
 * 
 * Generated by AMF for model: RelationshipsAndPregnancyData.metaabm in project: edu.brook.parent.escape 
 */
public class RelationshipsAndPregnancy3D extends RelationshipsAndPregnancy {

	public void createGraphicViews() {
		addView(new GEF3DView());
	}
}
