package edu.brook.ccf.rpm;

import org.eclipse.amp.escape.ascape.agf3d.GEF3DView;
import org.eclipse.amp.escape.ascape.adapt.Ascape3DPartFactory;
import org.eclipse.amp.agf3d.I3DModelFactoryProvider;
import org.eclipse.amp.escape.ascape.agf3d.GEF3DView;
import org.eclipse.swt.widgets.Display;
import org.eclipse.jface.viewers.IColorProvider;
import org.eclipse.gef.EditPartFactory;

/**
 * Relationships And Pregnancy Java Implementation.
 * 
 * Generated by AMF for model: RelationshipsAndPregnancyData.metaabm in project: edu.brook.parent.escape 
 */
public class RelationshipsAndPregnancy3D extends RelationshipsAndPregnancy
		implements
			I3DModelFactoryProvider {
	public void createGraphicViews() {
		addView(new GEF3DView());
	}

	public EditPartFactory getEditPart3DFactory() {
		return new Ascape3DPartFactory() {
			public IColorProvider getColorProvider(Object model) {

				if (model instanceof Adult) {
					return new edu.brook.ccf.rpm.GenderStyleColorProvider();
				}

				if (model instanceof NeighborhoodCell) {
					return new edu.brook.ccf.rpm.NeighborhoodCellStyle2DColorProvider();
				}

				return null;
			}
		};
	}

}
