package edu.brook.ccf.rpm;

/**
 * Relationships And Pregnancy Java Implementation.
 * 
 * Generated by metaabm system: Nov 23, 2009 4:41:04 PM PST in project: edu.brook.parent.escape  */
public class RPP3D3D extends RPP3D
		implements
			org.eclipse.amp.agf3d.I3DModelFactoryProvider {
	public void createGraphicViews() {
		addView(new org.eclipse.amp.escape.ascape.agf3d.GEF3DView());
	}

	public org.eclipse.gef.EditPartFactory getEditPart3DFactory() {
		return new org.eclipse.amp.escape.ascape.adapt.Ascape3DPartFactory() {
			public org.eclipse.jface.viewers.IColorProvider getColorProvider(
					Object object) {

				if (object instanceof Adult) {
					return new edu.brook.ccf.rpm.GenderStyleColorProvider();
				}

				if (object instanceof NeighborhoodCell) {
					return new edu.brook.ccf.rpm.NeighborhoodCellStyle2DColorProvider();
				}

				return null;
			}
		};
	}

}
